org.gradle.jvmargs=-Xmx2G
org.gradle.java.installations.auto-download=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1
loom_version=1.10-SNAPSHOT

mod_version=0.1.0
maven_group=com.adainish
archives_base_name=smearglespixelart
cobblemon_version=1.7.0+1.21.1
adventure_version=4.17.0
